export const corthay = {
    Calf: {
        label: 'Calf',
        colors: [
            'Ardillat',
            'Aubergine',
            'Autumn Leaves',
            'Avocado',
            'Black',
            'Blue',
            'Bois de Rose',
            'Bronze',
            'Caramel Brule',
            'Cognac',
            'Colvert',
            'Dark Blue',
            'Dark Red',
            'Ebony',
            'Grey',
            'Gun Metal',
            'Honey',
            'Lie de Vin',
            'Light Ebony',
            'Midori',
            'Moss',
            'Old Black',
            'Old Wood',
            'Olive',
            'Orenji',
            'Purple',
            'Red',
            'Ruby',
        ],
    },
    Suede: {
        label: 'Suede',
        colors: [
            'Amaranth',
            'Amber',
            'Aubergine',
            'Black',
            'Burgundy',
            'Castor',
            'Chagall',
            'Chardonnay',
            'Clay',
            'Dark Blue',
            'Dark Brown',
            'Electric Blue',
            'Feuille de Vigne',
            'Flint',
            'Grey',
            'Khaki',
            'Navy',
            'Squirrel',
        ],
    },
}

export const edwardGreen = {
    Calf: {
        label: 'Calf',
        colors: [
            'Acorn',
            'Bauxite',
            'Birch',
            'Black',
            'Bronze',
            'Burgundy',
            'Burnt Pine',
            'Chameleon',
            'Chestnut',
            'Cloud',
            'Dark Oak',
            'Edwardian',
            'Hazel',
            'Juniper',
            'Maple',
            'Midnight',
            'Navy',
            'Nightshade',
            'Old Rose',
            'Olive',
            'Redwood',
            'Slate',
            'White',
        ],
    },
    Suede: {
        label: 'Suede',
        colors: [
            'Aqua',
            'Army Green',
            'Berry Red',
            'Black',
            'Bluette',
            'Cardinal',
            'Clove',
            'Espresso',
            'Flannel',
            'Forest Green',
            'Indigo',
            'Lavagna',
            'Loden',
            'Mink',
            'Mocca',
            'Mole',
            'Mushroom',
            'Navy',
            'Nutmeg',
            'Oyster',
            'Smoke',
            'Snuff',
            'Tobacco',
            'White',
        ],
    },
    'Country Calf': {
        label: 'Country Calf',
        colors: [
            'Almond',
            'Black',
            'Grey',
            'Mahogany',
            'Navy',
            'Rosewood',
            'Walnut',
        ],
    },
    Delapre: {
        label: 'Delapre',
        colors: [
            'Black',
            'Blazer Blue',
            'Burgundy',
            'Damson',
            'Dark Brown',
            'Gold',
            'Racing Green',
        ],
    },
    Utah: {
        label: 'Utah',
        colors: [
            'Black',
            'Brown',
            'Burgundy',
            'Damson',
            'Gold',
            'Green',
            'Navy',
        ],
    },
    'London Grain': {
        label: 'London Grain',
        colors: ['Black', 'Burgundy', 'Dark Brown'],
    },
    'Shell Cordovan': {
        label: 'Shell Cordovan',
        colors: ['Black', 'Burgundy', 'Cognac', 'Navy', 'Whisky'],
    },
    Croc: {
        label: 'Croc',
        colors: ['Black', 'Dark Oak', 'Peanut'],
    },
    Patent: {
        label: 'Patent',
        colors: ['Black'],
    },
}

export const gazianoGirling = {
    Calf: {
        label: 'Calf',
        colors: [
            'Antique Grey',
            'Black',
            'Burgundy',
            'Espresso',
            'Midnight Blue',
            'Navy',
            'Pearl Grey',
            'Racing Green',
            'Vintage Cedar',
            'Vintage Cherry',
            'Vintage Chestnut',
            'Vintage Maple',
            'Vintage Oak',
            'Vintage Pine',
            'Vintage Rioja',
        ],
    },
    Suede: {
        label: 'Suede',
        colors: [
            'Black',
            'Burgundy',
            'Fox',
            'Green',
            'Grey',
            'Mink',
            'Mole',
            'Navy',
            'Polo',
            'Sandstone',
            'Tobacco',
        ],
    },
    'English Grain': {
        label: 'English Grain',
        colors: ['Black', 'Brown', 'Chestnut'],
    },
    'Hatch Grain': {
        label: 'Hatch Grain',
        colors: [
            'Black',
            'Espresso',
            'Navy',
            'Oak',
            'Racing Green',
            'Rioja',
            'Tan',
        ],
    },
    'Highland Grain': {
        label: 'Highland Grain',
        colors: ['Black', 'Brown', 'Burgundy', 'Chestnut', 'Rustic Arran'],
    },
    Pigskin: {
        label: 'Pigskin',
        colors: ['Black'],
    },
    'Pin Grain': {
        label: 'Pin Grain',
        colors: ['Black', 'Chestnut', 'Dark Brown'],
    },
}
